name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  merge-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true

      - name: Install gems
        run: bundle install

      - name: Build Debug
        run: bundle exec fastlane build_debug